version: '3.1'
services:
  studydso_db:
    container_name: studydso_db
    image: postgres:15.2
    restart: always
    ports:
      - 5445:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=studydso_pass
      - POSTGRES_USER=studydso_user
      - POSTGRES_DB=studydso_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U studydso_user -d studydso_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  lint:
    image: golangci/golangci-lint:v1.52.2
    profiles: ["tools"]
    volumes:
      - .:/app
    working_dir: /app

  migrate:
    image: migrate/migrate:v4.15.2
    profiles: ["tools"]
    volumes: 
      - ./db/migrations:/migrations
    entrypoint:
    [
      "migrate",
      "-path",
      "/migrations",
      "-database",
      "postgres://studydso_user:studydso_pass@studydso_db:5445/studydso_db?sslmode=disable"
    ]
    command: ["up"]
    depends_on:
      studydso_db:
        condition: service_healthy
        restart: false

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8004:8080"
    volumes:
      - ./docs:/docs
    environment:
      - SWAGGER_JSON=/docs/api.yml
      - BASE_URL=/swagger
    # env_file:
    #   - app.env
volumes:
  postgres_data: